# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Build release
      run: ./build.sh

    - name: Tag release
      run: git tag "v$(cat version.txt)"

    - name: Push tag
      run: git push "v$(cat version.txt)"

    - name: Create release
      uses: Roang-zero1/github-create-release-action@v2
      with:
        version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "bin/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
